image : "node:10.16.0"

stages :
  - build
  - serve

cache : 
  paths :
    - node_modules/

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

serve_Project:
  stage : serve
  script : npm run serve
